### ISSUE TITLE
Pass original message

### ISSUE THREAD

**Issue by smcgann99** [soloam/node-red-contrib-colorspace#3]
Hi,
Thanks for your useful node, I'm trying to use it with Alexa but noticed you create a new payload. 
Would it be possible to add your data to the existing msg so I can for example read the info from Alexa - 
command: "SetColorRequest"

I believe its a node red standard to add extra info rather than replace the msg.

Thanks

**Comment by soloam** [comment]
> Hi,
> Thanks for your useful node, I'm trying to use it with Alexa but noticed you create a new payload. 
> Would it be possible to add your data to the existing msg so I can for example read the info from Alexa - 
> command: "SetColorRequest"
> 
> I believe its a node red standard to add extra info rather than replace the msg.
> 
> Thanks

Hello, aren't you able to set the target and select whatever variable to use? Payload is the default, but you should be able to use any other variable that you desire!

Thank you

**Comment by smcgann99** [comment]
So sorry I didn't notice that thanks!!
